# Generated by Django 5.1.3 on 2025-01-19 11:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_user_country"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="username",
        ),
    ]
